CREATE TABLE "RGT_USR" 
(	
    "ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(500) NOT NULL ENABLE, 
	"USRNM" VARCHAR2(50) NOT NULL ENABLE, 
	"PSWRD" VARCHAR2(50) NOT NULL ENABLE,
	"RQRMNT_CRT" VARCHAR2(3) NOT NULL ENABLE, 
	"RQRMNT_RD" VARCHAR2(3) NOT NULL ENABLE, 
	"RQRMNT_UPDT" VARCHAR2(3) NOT NULL ENABLE, 
	"RQRMNT_DLT" VARCHAR2(3) NOT NULL ENABLE, 
	"DT_ENTY_CRT" VARCHAR2(3) NOT NULL ENABLE, 
	"DT_ENTY_RD" VARCHAR2(3) NOT NULL ENABLE, 
	"DT_ENTY_UPDT" VARCHAR2(3) NOT NULL ENABLE, 
	"DT_ENTY_DLT" VARCHAR2(3) NOT NULL ENABLE,
	"IS_SPR_USR" VARCHAR2(3) NOT NULL ENABLE,
	"ORGNZTN_ID" NUMBER NOT NULL ENABLE, 
	"CRTN_DT" TIMESTAMP NOT NULL ENABLE, 
	"CRTD_BY_USR_ID" NUMBER NOT NULL ENABLE, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE SEQUENCE "RGT_USR_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_PK1" PRIMARY KEY ("ID");
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_UK1" UNIQUE ("USRNM", "ORGNZTN_ID");
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_FK1" FOREIGN KEY ("CRTD_BY_USR_ID") REFERENCES "RGT_USR"("ID");
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_FK2" FOREIGN KEY ("MDFD_BY_USR_ID") REFERENCES "RGT_USR"("ID");
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_CHK1" CHECK ("RQRMNT_CRT" in ('YES','NO'));
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_CHK2" CHECK ("RQRMNT_RD" in ('YES','NO'));
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_CHK3" CHECK ("RQRMNT_UPDT" in ('YES','NO'));
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_CHK4" CHECK ("RQRMNT_DLT" in ('YES','NO'));
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_CHK5" CHECK ("DT_ENTY_CRT" in ('YES','NO'));
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_CHK6" CHECK ("DT_ENTY_RD" in ('YES','NO'));
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_CHK7" CHECK ("DT_ENTY_UPDT" in ('YES','NO'));
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_CHK8" CHECK ("DT_ENTY_DLT" in ('YES','NO'));
ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_CHK9" CHECK ("IS_SPR_USR" in ('YES','NO'));

CREATE TABLE "RGT_ORGNZTN" 
(
    "ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(500) NOT NULL ENABLE, 
	"CRTN_DT" TIMESTAMP NOT NULL ENABLE, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE SEQUENCE "RGT_ORGNZTN_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

ALTER TABLE "RGT_ORGNZTN" ADD CONSTRAINT "RGT_ORGNZTN_PK1" PRIMARY KEY ("ID");
ALTER TABLE "RGT_ORGNZTN" ADD CONSTRAINT "RGT_ORGNZTN_UK1" UNIQUE ("NAME");
ALTER TABLE "RGT_ORGNZTN" ADD CONSTRAINT "RGT_ORGNZTN_FK1" FOREIGN KEY ("CRTD_BY_USR_ID") REFERENCES "RGT_USR"("ID");
ALTER TABLE "RGT_ORGNZTN" ADD CONSTRAINT "RGT_ORGNZTN_FK2" FOREIGN KEY ("MDFD_BY_USR_ID") REFERENCES "RGT_USR"("ID");

ALTER TABLE "RGT_USR" ADD CONSTRAINT "RGT_USR_FK3" FOREIGN KEY ("ORGNZTN_ID") REFERENCES "RGT_ORGNZTN"("ID");

CREATE TABLE "RGT_DT_ENTY" 
(
	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(500) NOT NULL ENABLE, 
	"ORGNZTN_ID" NUMBER NOT NULL, 
	"CRTN_DT" TIMESTAMP NOT NULL ENABLE, 
	"CRTD_BY_USR_ID" NUMBER NOT NULL ENABLE, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000),
	"CLMN1" VARCHAR2(100),
	"CLMN2" VARCHAR2(100)
);

CREATE SEQUENCE "RGT_DT_ENTY_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

ALTER TABLE "RGT_DT_ENTY" ADD CONSTRAINT "RGT_DT_ENTY_PK1" PRIMARY KEY ("ID");
ALTER TABLE "RGT_DT_ENTY" ADD CONSTRAINT "RGT_DT_ENTY_UK1" UNIQUE ("NAME", "ORGNZTN_ID");
ALTER TABLE "RGT_DT_ENTY" ADD CONSTRAINT "RGT_DT_ENTY_FK1" FOREIGN KEY ("CRTD_BY_USR_ID") REFERENCES "RGT_USR"("ID");
ALTER TABLE "RGT_DT_ENTY" ADD CONSTRAINT "RGT_DT_ENTY_FK2" FOREIGN KEY ("MDFD_BY_USR_ID") REFERENCES "RGT_USR"("ID");
ALTER TABLE "RGT_DT_ENTY" ADD CONSTRAINT "RGT_DT_ENTY_FK3" FOREIGN KEY ("ORGNZTN_ID") REFERENCES "RGT_ORGNZTN"("ID");

CREATE TABLE "RGT_RQRMNT" 
(
	"ID" NUMBER NOT NULL ENABLE,
	"RQRMNT_TXT" VARCHAR2(4000) NOT NULL,
	"ORGNZTN_ID" NUMBER NOT NULL,
	"CRTN_DT" TIMESTAMP NOT NULL ENABLE,
	"CRTD_BY_USR_ID" NUMBER NOT NULL ENABLE, 
	"MDFCTN_DT" TIMESTAMP,
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);


CREATE SEQUENCE "RGT_RQRMNT_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

ALTER TABLE "RGT_RQRMNT" ADD CONSTRAINT "RGT_RQRMNT_PK1" PRIMARY KEY ("ID");
ALTER TABLE "RGT_RQRMNT" ADD CONSTRAINT "RGT_RQRMNT_FK1" FOREIGN KEY ("CRTD_BY_USR_ID") REFERENCES "RGT_USR"("ID");
ALTER TABLE "RGT_RQRMNT" ADD CONSTRAINT "RGT_RQRMNT_FK2" FOREIGN KEY ("MDFD_BY_USR_ID") REFERENCES "RGT_USR"("ID");
ALTER TABLE "RGT_RQRMNT" ADD CONSTRAINT "RGT_RQRMNT_FK3" FOREIGN KEY ("ORGNZTN_ID") REFERENCES "RGT_ORGNZTN"("ID");

CREATE TABLE "RGT_DT_ENTY_HRCHY"
(
	"ID" NUMBER NOT NULL,
	"DT_ENTY_ID" NUMBER NOT NULL,
	"PRNT_DT_ENTY_ID" NUMBER NOT NULL,
	"CRTN_DT" TIMESTAMP NOT NULL,
	"CRTD_BY_USR_ID" NUMBER NOT NULL,
	"MDFCTN_DT" TIMESTAMP,
	"MDFD_BY_USR_ID" NUMBER,
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE SEQUENCE "RGT_DT_ENTY_HRCHY_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

ALTER TABLE "RGT_DT_ENTY_HRCHY" ADD CONSTRAINT "RGT_DT_ENTY_HRCHY_PK" PRIMARY KEY ("ID");
ALTER TABLE "RGT_DT_ENTY_HRCHY" ADD CONSTRAINT "RGT_DT_ENTY_HRCHY_FK1" FOREIGN KEY ("DT_ENTY_ID") REFERENCES "RGT_DT_ENTY"("ID");
ALTER TABLE "RGT_DT_ENTY_HRCHY" ADD CONSTRAINT "RGT_DT_ENTY_HRCHY_FK2" FOREIGN KEY ("PRNT_DT_ENTY_ID") REFERENCES "RGT_DT_ENTY"("ID");
ALTER TABLE "RGT_DT_ENTY_HRCHY" ADD CONSTRAINT "RGT_DT_ENTY_HRCHY_FK3" FOREIGN KEY ("CRTD_BY_USR_ID") REFERENCES "RGT_USR"("ID");
ALTER TABLE "RGT_DT_ENTY_HRCHY" ADD CONSTRAINT "RGT_DT_ENTY_HRCHY_FK4" FOREIGN KEY ("MDFD_BY_USR_ID") REFERENCES "RGT_USR"("ID");


CREATE TABLE "RGT_DT_ENTY_RQRMNT_MP" 
(
	"ID" NUMBER NOT NULL ENABLE,
	"DT_ENTY_ID" NUMBER NOT NULL ENABLE,
	"RQRMNT_ID" NUMBER NOT NULL ENABLE,
	"CRTN_DT" TIMESTAMP NOT NULL ENABLE, 
	"CRTD_BY_USR_ID" NUMBER NOT NULL ENABLE, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE SEQUENCE "RGT_DT_ENTY_RQRMNT_MP_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;

ALTER TABLE "RGT_DT_ENTY_RQRMNT_MP" ADD CONSTRAINT "RGT_DT_ENTY_RQRMNT_MP_PK" PRIMARY KEY ("ID");
ALTER TABLE "RGT_DT_ENTY_RQRMNT_MP" ADD CONSTRAINT "RGT_DT_ENTY_RQRMNT_MP_UK1" UNIQUE ("DT_ENTY_ID", "RQRMNT_ID");
ALTER TABLE "RGT_DT_ENTY_RQRMNT_MP" ADD CONSTRAINT "RGT_DT_ENTY_RQRMNT_MP_FK1" FOREIGN KEY ("DT_ENTY_ID") REFERENCES "RGT_DT_ENTY"("ID");
ALTER TABLE "RGT_DT_ENTY_RQRMNT_MP" ADD CONSTRAINT "RGT_DT_ENTY_RQRMNT_MP_FK2" FOREIGN KEY ("RQRMNT_ID") REFERENCES "RGT_RQRMNT"("ID");
ALTER TABLE "RGT_DT_ENTY_RQRMNT_MP" ADD CONSTRAINT "RGT_DT_ENTY_RQRMNT_MP_FK3" FOREIGN KEY ("CRTD_BY_USR_ID") REFERENCES "RGT_USR"("ID");
ALTER TABLE "RGT_DT_ENTY_RQRMNT_MP" ADD CONSTRAINT "RGT_DT_ENTY_RQRMNT_MP_FK4" FOREIGN KEY ("MDFD_BY_USR_ID") REFERENCES "RGT_USR"("ID");

------------------------------------------------------------------------------------------

CREATE TABLE "A_ORGNZTN" 
(
	"PK_ID" NUMBER NOT NULL, 
	"ORGNZTN_NM" VARCHAR2(500) NOT NULL, 
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE TABLE "A_USR"
(
	"PK_ID" NUMBER NOT NULL, 
	"USRNM" VARCHAR2(50) NOT NULL, 
	"PSWRD" VARCHAR2(50), 
	"RQRMNT_CRT" VARCHAR2(3) NOT NULL, 
	"RQRMNT_RD" VARCHAR2(3) NOT NULL, 
	"RQRMNT_UPDT" VARCHAR2(3) NOT NULL, 
	"RQRMNT_DLT" VARCHAR2(3) NOT NULL, 
	"DT_ENTY_CRT" VARCHAR2(3) NOT NULL, 
	"DT_ENTY_RD" VARCHAR2(3) NOT NULL, 
	"DT_ENTY_UPDT" VARCHAR2(3) NOT NULL, 
	"DT_ENTY_DLT" VARCHAR2(3) NOT NULL, 
	"USR_CRT" VARCHAR2(3) NOT NULL, 
	"USR_RD" VARCHAR2(3) NOT NULL, 
	"USR_UPDT" VARCHAR2(3) NOT NULL, 
	"USR_DLT" VARCHAR2(3) NOT NULL, 
	"ORGNZTN_ID" NUMBER NOT NULL, 
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE TABLE "A_RQRMNT" 
(
	"PK_ID" NUMBER NOT NULL, 
	"UNQ_ID" NUMBER NOT NULL, 
	"RVSN_NMBR" NUMBER NOT NULL,
	"CRNT_RVSN_IND" VARCHAR2(3) NOT NULL,
	"RQRMNT_TEXT" VARCHAR2(4000) NOT NULL,
	"ORGNZTN_ID" NUMBER NOT NULL, 
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000),
	"CLMN1" VARCHAR2(100),
	"CLMN2" VARCHAR2(100),
	"CLMN3" VARCHAR2(100),
	"CLMN4" VARCHAR2(100),
	"CLMN5" VARCHAR2(100),
	"CLMN6" VARCHAR2(100),
	"CLMN7" VARCHAR2(100),
	"CLMN8" VARCHAR2(100),
	"CLMN9" VARCHAR2(100),
	"CLMN0" VARCHAR2(100)
);

CREATE TABLE "A_DT_ENTY" 
(
	"PK_ID" NUMBER NOT NULL, 
	"UNQ_ID" NUMBER NOT NULL, 
	"RVSN_NMBR" NUMBER NOT NULL,
	"CRNT_RVSN_IND" VARCHAR2(3) NOT NULL,
	"DT_ENTY_NM" VARCHAR2(100) NOT NULL,
	"ORGNZTN_ID" NUMBER NOT NULL, 
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000),
	"CLMN1" VARCHAR2(100),
	"CLMN2" VARCHAR2(100),
	"CLMN3" VARCHAR2(100),
	"CLMN4" VARCHAR2(100),
	"CLMN5" VARCHAR2(100),
	"CLMN6" VARCHAR2(100),
	"CLMN7" VARCHAR2(100),
	"CLMN8" VARCHAR2(100),
	"CLMN9" VARCHAR2(100),
	"CLMN10" VARCHAR2(100)
);

CREATE TABLE "A_DT_ENTY_RQRMNT_MP" 
(
	"PK_ID" NUMBER NOT NULL,
	"RQRMNT_ID" NUMBER NOT NULL,
	"DT_ENTY_ID" NUMBER NOT NULL,
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE TABLE "A_DT_ENTY_HRCHY_MP" 
(
	"PK_ID" NUMBER NOT NULL,
	"DT_ENTY_ID" NUMBER NOT NULL,
	"PRNT_DT_ENTY_ID" NUMBER NOT NULL,
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE TABLE "A_RQRMNT_HRCHY_MP" 
(
	"PK_ID" NUMBER NOT NULL,
	"RQRMNT_ID" NUMBER NOT NULL,
	"PRNT_RQRMNT_ID" NUMBER NOT NULL,
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE TABLE "A_RQRMNT_PRCS_FLW_MP" 
(
	"PK_ID" NUMBER NOT NULL,
	"RQRMNT_ID" NUMBER NOT NULL,
	"PRDCSR_RQRMNT_ID" NUMBER NOT NULL,
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE TABLE "A_RQRMNT_CLMN_NM_MP" 
(
	"PK_ID" NUMBER NOT NULL, 
	"TBL_CLMN_NM" VARCHAR2(100) NOT NULL, 
	"USR_FRNDLY_CLMN_NM" VARCHAR2(100) NOT NULL,
	"ORGNZTN_ID" NUMBER NOT NULL, 
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE TABLE "A_DT_ENTY_CLMN_NM_MP" 
(
	"PK_ID" NUMBER NOT NULL, 
	"TBL_CLMN_NM" VARCHAR2(100) NOT NULL, 
	"USR_FRNDLY_CLMN_NM" VARCHAR2(100) NOT NULL,
	"ORGNZTN_ID" NUMBER NOT NULL, 
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE TABLE "A_USR_RQRMNT_CLMN_MP" 
(
	"PK_ID" NUMBER NOT NULL,
	"USR_ID" NUMBER NOT NULL,
	"TBL_CLMN_NM" VARCHAR2(100) NOT NULL,
	"SQUNC_NMBR" NUMBER NOT NULL,
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

CREATE TABLE "A_USR_DT_ENTY_CLMN_MP" 
(
	"PK_ID" NUMBER NOT NULL,
	"USR_ID" NUMBER NOT NULL,
	"TBL_CLMN_NM" VARCHAR2(100) NOT NULL,
	"SQNC_NMBR" NUMBER NOT NULL,
	"CRTN_DT" TIMESTAMP NOT NULL, 
	"CRTD_BY_USR_ID" NUMBER, 
	"MDFCTN_DT" TIMESTAMP, 
	"MDFD_BY_USR_ID" NUMBER, 
	"MDFCTN_CMNT" VARCHAR2(2000)
);

-- Constraints

ALTER TABLE "A_ORGNZTN" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_USR" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_RQRMNT" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_DT_ENTY" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_DT_ENTY_RQRMNT_MP" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_DT_ENTY_HRCHY_MP" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_RQRMNT_HRCHY_MP" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_RQRMNT_PRCS_FLW_MP" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_RQRMNT_CLMN_NM_MP" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_DT_ENTY_CLMN_NM_MP" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_USR_RQRMNT_CLMN_MP" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");
ALTER TABLE "A_USR_DT_ENTY_CLMN_MP" ADD CONSTRAINT "PK" PRIMARY KEY ("PK_ID");

ALTER TABLE "A_USR" ADD CONSTRAINT "CHK_RQRMNT_CRT_VAL" CHECK ("RQRMNT_CRT" in ('YES','NO'));
ALTER TABLE "A_USR" ADD CONSTRAINT "CHK_RQRMNT_RD_VAL" CHECK ("RQRMNT_RD" in ('YES','NO'));

ALTER TABLE "A_ORGNZTN" ADD CONSTRAINT "NOT_NULL_CRTD_BY_USR_ID" CHECK("CRTD_BY_USR_ID" IS NOT NULL);

-- Sequence

CREATE SEQUENCE "A_ORGNZTN_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_USR_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_RQRMNT_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_DT_ENTY_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_DT_ENTY_RQRMNT_MP_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_DT_ENTY_HRCHY_MP_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_RQRMNT_HRCHY_MP_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_RQRMNT_PRCS_FLW_MP_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_RQRMNT_CLMN_NM_MP_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_DT_ENTY_CLMN_NM_MP_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_USR_RQRMNT_CLMN_MP_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_USR_DT_ENTY_CLMN_MP_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_RQRMNT_UNQ_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
CREATE SEQUENCE "A_DT_ENTY_UNQ_SEQ" MINVALUE 1 START WITH 1 INCREMENT BY 1 CACHE 10;
